name: AntiGoldFarm
version: '${version}'
main: net.bordermc.antiGoldFarm.AntiGoldFarm
author: BorderMC
api-version: '1.21.11'
website: https://bordermc.net
load: POSTWORLD

permissions:
  antigoldfarm.reload:
    description: Allows to reload the configuration file.
    default: op

commands:
  antigoldfarm:
    description: Commands related to antigoldfarm.
    permission: antigoldfarm.reload
    permission-message: You don't have the permission to use this command.
